# Generated by Django 6.0.5 on 2026-05-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usersettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='theme',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='color_scheme',
            field=models.CharField(choices=[('cyan', 'Циан (по умолчанию)'), ('blue', 'Синий'), ('green', 'Зелёный'), ('purple', 'Фиолетовый')], default='cyan', max_length=10, verbose_name='Цветовая схема'),
        ),
    ]
