# Generated by Django 6.0.5 on 2026-05-14 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0002_alter_request_options_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': 'Обращение', 'verbose_name_plural': 'Обращения'},
        ),
    ]
