# Generated by Django 6.0.5 on 2026-05-14 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requests_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/', verbose_name='Файл документа')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('doc_type', models.CharField(max_length=50, verbose_name='Тип документа')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='requests_app.request')),
            ],
        ),
    ]
